<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;

/**
 * What the tunnel's address answers.
 *
 * The rules live on this machine, in the config cloudflared reads, so opening
 * the site up or shutting it again is a local file and a restart — no server
 * to log into, and nothing on the production box involved at all.
 *
 *   hooks  (the resting state)  the webhook paths; everything else 404s
 *   site                        the whole development site
 *   off                         nothing
 */
class TunnelModeCommand extends Command
{
    protected $signature = 'tunnel:mode {mode? : hooks, site, off, or nothing to see what is set}';

    protected $description = 'Choose what the development tunnel lets through';

    /** @var list<string> */
    private const MODES = ['hooks', 'site', 'off'];

    public function handle(): int
    {
        if ($this->getLaravel()->isProduction()) {
            $this->error('Run this from a development machine.');

            return self::FAILURE;
        }

        $mode = $this->argument('mode');

        if ($mode === null) {
            $this->line('  mode: <fg=cyan>'.self::currentMode().'</>');
            $this->line('  <fg=gray>'.implode(', ', self::MODES).'</>');

            return self::SUCCESS;
        }

        if (! in_array($mode, self::MODES, true)) {
            $this->error("Unknown mode \"{$mode}\". One of: ".implode(', ', self::MODES).'.');

            return self::FAILURE;
        }

        // Before the file, not after: on a machine that has never run
        // `tunnel:setup` there is nowhere to put it yet.
        TunnelCommand::ensureDirectory();
        File::put(self::modeFile(), $mode);
        self::writeConfig();

        $this->line('  mode: <fg=cyan>'.$mode.'</>');

        if ($mode === 'site') {
            $this->warn('  The whole development site now answers on that address.');
            $this->line('  <fg=gray>Half-finished pages, test data and the admin area. Put it back with `php artisan tunnel:mode hooks`.</>');
        }

        $this->line('  <fg=gray>Restart `php artisan tunnel` for this to take effect.</>');

        return self::SUCCESS;
    }

    /** The mode this machine is set to; webhooks only until told otherwise. */
    public static function currentMode(): string
    {
        $file = self::modeFile();

        return is_file($file) ? trim(File::get($file)) : 'hooks';
    }

    /**
     * Writes the ingress rules cloudflared reads.
     *
     * Generated rather than hand-kept: the paths come from config/tunnel.php,
     * so adding one is an edit to settings and a restart, and the file on disk
     * can never disagree with them. A path that is not listed is refused by
     * Cloudflare and never reaches this machine.
     */
    public static function writeConfig(): void
    {
        TunnelCommand::ensureDirectory();

        $domain = (string) config('tunnel.domain');
        $service = (string) config('tunnel.local_url');
        $host = (string) config('tunnel.local_host');
        $mode = self::currentMode();

        $lines = [
            '# Generated by `php artisan tunnel:mode` — edit config/tunnel.php instead.',
            'tunnel: '.config('tunnel.name'),
            'credentials-file: '.self::credentialsFile(),
            '',
            'ingress:',
        ];

        if ($mode !== 'off') {
            foreach ((array) config('tunnel.webhook_paths') as $path) {
                $lines[] = '  - hostname: '.$domain;
                // Anchored: `/api/paddle/webhook` and nothing that merely
                // starts with it.
                // No delimiter: Cloudflare reads this as a Go regular
                // expression, where an escaped slash is not a valid escape at
                // all — it would refuse the config rather than match the path.
                $lines[] = '    path: ^'.preg_quote($path).'$';
                $lines[] = '    service: '.$service;
                $lines[] = '    originRequest:';
                $lines[] = '      httpHostHeader: '.$host;
            }
        }

        if ($mode === 'site') {
            $lines[] = '  - hostname: '.$domain;
            $lines[] = '    service: '.$service;
            $lines[] = '    originRequest:';
            $lines[] = '      httpHostHeader: '.$host;
        }

        // Cloudflare requires a catch-all, and ours refuses.
        $lines[] = '  - service: http_status:404';
        $lines[] = '';

        File::put((string) config('tunnel.config_path'), implode("\n", $lines));
    }

    private static function modeFile(): string
    {
        return dirname((string) config('tunnel.config_path')).'/mode';
    }

    /**
     * The tunnel's own credentials, written by `cloudflared tunnel create`.
     * Machine-specific, so it lives beside the generated config and not in
     * the repository.
     */
    private static function credentialsFile(): string
    {
        return dirname((string) config('tunnel.config_path')).'/'.config('tunnel.name').'.json';
    }
}
